gcloud compute --project "serious-habitat-123456" instances create "coreos-rower-test" \
  --zone "europe-west1-d" \
  --machine-type "n1-standard-1" \
  --network "default" \
  --metadata-from-file "user-data=cloud-config.yml","kube-pods=example-userdata.yaml" \
  --maintenance-policy "MIGRATE" \
  --scopes default="https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write","https://www.googleapis.com/auth/cloud.useraccounts.readonly" \
  --image "/coreos-cloud/coreos-alpha-1010-1-0-v20160407" \
  --boot-disk-size "10" \
  --boot-disk-type "pd-ssd" \
  --boot-disk-device-name "coreos-rower-test"
